language: go

go:
  - 1.1
  - tip

env:
  global:
    - secure: "dv0y3foD7LdFxYGjI5Frgb1RfDsMA4pebO3luucdjjQT5zTkjnpYkHH55ZcXRppVW7eqO0sbSTUPbzx2YfHZh+aUx3/VDRCKocW8S65OeJ8VSJH0LIbxQNs+N7BAyVZfBOfo4Uv7WEJOM6Yfn2QgfrIvQa/KOjtCuTRnVXEUO3o="
    - secure: "cjZiZo9q0Y35es+KWA21Z69bY76ssftDQ6zVHHNqkDw9gug59Bv9WBA4WBV/TiN/i1WOjPNxFFRVke4dy5c9l2H4gHnbB29MtjohdhtAt8ra4UydiD9adau2vK+8Jsvoef9KPMYLx6E+JUSeHUgU9baWiVbBA67lcE4DKAnWRWY="

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install git mercurial
 

install:
 - cd server
 - cp .config.go.travis config.go
 - echo $CLIENT_ID >> config.go
 - echo $CLIENT_SECRET >> config.go
 - bash install.sh

script: